graph_scale:
  individuals: 50
  businesses: 10
  institutions: 3
  individual_accounts_per_institution_range: [1, 3]
  business_accounts_per_institution_range: [1, 6]
transaction_rates:
  per_account_per_day: 1
time_span:
  start_date: '2023-01-01T00:00:00'
  end_date: '2023-03-15T23:59:59'
account_balance_range_normal: [1000.0, 50000.0]
background_amount_range: [10.0, 500.0]
company_size_range: [1, 1000]
salary_payment_days: [24, 30, 1]
salary_amount_range: [2500.0, 7500.0]
business_creation_date_range: [90, 5475]
individual_business_ownership_rate: 0.2

age_group_business_probabilities:
  "18-24": 0.5
  "25-34": 2.0
  "35-49": 1.8
  "50-64": 1.0
  "65+": 0.3

pattern_frequency:
  num_illicit_patterns: 5
amount_distribution_params:
  mean: 100
  variance: 50
high_transaction_amount_ratio: 0.05
low_transaction_amount_ratio: 0.1

account_categories:
  - "Current"
  - "Savings"
  - "Loan"
  - "Business"